MVCegitimi/Controllers/Mvc11SessionCookieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCegitimi.Controllers
{
    public class Mvc11SessionCookieController : Controller
    {
        // GET: Mvc11SessionCookie
        public ActionResult Index()
        {
            if (HttpContext.Request.Cookies["kullanici"] != null)
            {
                ViewBag.kuki=HttpContext.Request.Cookies["kullanici"].Value;
            }
            return View();
        }
        public ActionResult Sessions() //ilgili session ı yakalayıp göstereceğimi sayfa
        {
            if (Session["deger"] != null)
            {
                ViewBag.SessDeger = Session["deger"].ToString();
            }
            else
            {
                ViewBag.SessDeger = " Session değeri boş";
            }
            return View();
        }
        [HttpPost]
        public ActionResult Sessions(string text) //ilgili session ı yakalayıp Sil
        {
            if (Session["deger"] != null)
            {
                //Session["deger"]=null;  //2.yöntem
                Session.Remove("deger");
            }
            else
            {
                ViewBag.SessDeger = " Session değeri boş";
            }
            return View();
        }
        [HttpPost]
        public ActionResult Index(string text)
        {
            //Index teki text yazan sessiondaki değeri tutar (string text sayesinde)
            Session["deger"] = text;
            //Session.Add("deger", text);//2. yöntem
            return View();
        }
        public ActionResult CookieOlustur(string kuki)
        {
            HttpCookie cookie = new HttpCookie("kullanici", "kuki"); //cookie olusturma
            HttpContext.Response.Cookies.Add(cookie); //oluşan cookie yi cihaza atma
            ViewBag.Kullanici = HttpContext.Request.Cookies["kullanici"].Value;// cihazdan okuma
            return View("Index");
        }
        public ActionResult CookieSil()
        {
            if (HttpContext.Request.Cookies["kullanici"] != null)
            {
                HttpContext.Response.Cookies["kullanici"].Expires = DateTime.Now.AddSeconds(-3);
                ViewBag.Kullanici = "kuki silindi";
            }

            return RedirectToAction("Index");//View("Index");
        }
    }
}

MVCegitimi/Views/Mvc11SessionCookie/Index.cshtml
@{
    ViewBag.Title = "Mvc Session cookie kullanımı";
}
<h2>Mvc Session cookie kullanımı</h2>

@using (Html.BeginForm())
{
    <h4>Session Oluşturma</h4>
    @Html.TextBox("text", "sess")
    <input id="Submit1" type="submit" value="session oluştur" />
}

<hr />
@using (Html.BeginForm("CookieOlustur", "Mvc11SessionCookie"))
{
    <h4>Cookie Oluşturma</h4>
    @Html.TextBox("kuki", "kuki")
    <input id="Submit1" type="submit" value="cookie oluştur" />
}
<hr />
@ViewBag.kuki
<hr />

@using (Html.BeginForm("CookieSil", "Mvc11SessionCookie"))
{
    <h4>Cookie Sil</h4>
    <input id="Submit1" type="submit" value="Cookie sil" />
}

MVCegitimi/Views/Mvc11SessionCookie/Sessions.cshtml
@{
    ViewBag.Title = "Sessions";
}

<h2>Sessions</h2>
@ViewBag.SessDeger
<hr />
@using (Html.BeginForm())
{
    <h4>Session Sil</h4>
    <input id="Submit1" type="submit" value="session sil" />
}